### ISSUE TITLE
Update Notebooks Schema

### ISSUE THREAD

**Issue by chrisdedman** [Code-Society-Lab/cursif-backend#21]
Need to update the Notebook Query to add the following info:
```
inserted_at: DateTime.t(),
updated_at: DateTime.t()
```
- Once implemented, need to edit [Notebooks Dashboard](https://github.com/Code-Society-Lab/cursif-web/blob/23ad5d38c565a082f885ebc06dff4d95dbc86279/src/components/notebooks/card.tsx#L5) with the corresponding data. 
- Related PR for the frontend https://github.com/Code-Society-Lab/cursif-web/issues/38

#### Hint
Look at the [notebook_types.ex](https://github.com/Code-Society-Lab/cursif-backend/blob/main/lib/cursif_web/schemas/types/notebook_types.ex) file and add the required fields.

**Comment by PenguinBoi12** [comment]
Done! `inserted_at` and `updated_at` are now available in the notebook schema.
